#!/usr/bin/env bash
#
# gen-corpus.sh — generate benchmark corpora for AudioTag under bench-data/.
#
# The corpora are deliberately *format-diverse* and (for one corpus)
# *art-bearing*, because the previous WAV-only set hid the real per-file parse
# cost (WAV tags are trivial and carry no embedded art).
#
# Strategy: build one fully-tagged "template" file per format with ffmpeg, then
# replicate templates by copying them into a nested directory tree with unique
# names. Copying is fast and idempotent; per-file tag *content* doesn't matter
# for scan/parse benchmarks (the parse cost is identical), and the save
# benchmark mutates tags itself.
#
# Requires: ffmpeg (with libmp3lame, flac, aac, vorbis, libopus, wavpack,
# pcm_s16le/be encoders — all present in a standard build).
#
# Usage:
#   scripts/gen-corpus.sh [corpus ...]      # generate the named corpora
#   scripts/gen-corpus.sh all               # everything except large/art-heavy
#   scripts/gen-corpus.sh large art-heavy   # the heavy ones (multi-GB)
#   FORCE=1 scripts/gen-corpus.sh small     # regenerate even if present
#
# Corpus sizes are overridable: TINY=, SMALL=, MEDIUM=, LARGE=, DEEP=,
# ART=, CORRUPT=, DIRTY_SMALL=, DIRTY_LARGE=.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA="$ROOT/bench-data"
TPL="$DATA/.templates"

TINY="${TINY:-100}"
SMALL="${SMALL:-1000}"
MEDIUM="${MEDIUM:-5000}"
LARGE="${LARGE:-20000}"
DEEP="${DEEP:-5000}"
ART="${ART:-1000}"
CORRUPT="${CORRUPT:-200}"
DIRTY_SMALL="${DIRTY_SMALL:-500}"
DIRTY_LARGE="${DIRTY_LARGE:-2000}"

# Formats we can synthesize (every ffmpeg-encodable AUDIO_EXTS entry). ape, mpc
# and spx are intentionally omitted: ffmpeg has no encoder for them. lofty still
# reads/writes those; they're just not represented in the generated corpora.
FORMATS=(mp3 flac m4a ogg opus wav aiff wv)

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "error: ffmpeg is required (brew install ffmpeg / apt install ffmpeg)." >&2
  exit 1
fi

log() { printf '\033[36m›\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------------------
# ffmpeg encoder args per extension
# ---------------------------------------------------------------------------
enc_args() {
  case "$1" in
    mp3)  echo "-c:a libmp3lame -q:a 9" ;;
    flac) echo "-c:a flac -compression_level 0" ;;
    m4a)  echo "-c:a aac -b:a 32k" ;;
    ogg)  echo "-c:a vorbis -strict experimental -q:a 0" ;;
    opus) echo "-c:a libopus -b:a 24k" ;;
    wav)  echo "-c:a pcm_s16le" ;;
    aiff) echo "-c:a pcm_s16be" ;;
    wv)   echo "-c:a wavpack" ;;
    *) echo "unknown format: $1" >&2; exit 1 ;;
  esac
}

META=(-metadata title="Benchmark Track" \
      -metadata artist="The Benchmarks" \
      -metadata album="Corpus Vol. 1" \
      -metadata album_artist="Various Artists" \
      -metadata track="5/12" \
      -metadata disc="1/2" \
      -metadata date="2024" \
      -metadata genre="Electronic" \
      -metadata comment="generated by gen-corpus.sh" \
      -metadata composer="A. Composer")

# Build the tagged template files (one per format). Cheap; always refreshed.
build_templates() {
  mkdir -p "$TPL"
  local sr ext cl
  for ext in "${FORMATS[@]}"; do
    [ -f "$TPL/template.$ext" ] && [ -z "${FORCE:-}" ] && continue
    # opus only supports 48 kHz; everything else uses 44.1 kHz.
    sr=44100; [ "$ext" = opus ] && sr=48000
    # ffmpeg's native vorbis encoder only accepts stereo input.
    cl=mono; [ "$ext" = ogg ] && cl=stereo
    # shellcheck disable=SC2046
    ffmpeg -hide_banner -loglevel error -y \
      -f lavfi -i "anullsrc=channel_layout=$cl:sample_rate=$sr" -t 1 \
      $(enc_args "$ext") "${META[@]}" "$TPL/template.$ext"
  done
  log "templates ready: ${FORMATS[*]}"
}

# Build art-bearing templates (large random-noise JPEG covers, ~3 MB each).
# Only formats with robust picture support are used for the art corpus.
ART_FORMATS=(flac mp3 m4a)
build_art_templates() {
  mkdir -p "$TPL"
  local cover="$TPL/cover.jpg"
  if [ ! -f "$cover" ] || [ -n "${FORCE:-}" ]; then
    # Random noise defeats JPEG compression, yielding a chunky (~3 MB) cover.
    ffmpeg -hide_banner -loglevel error -y \
      -f rawvideo -pix_fmt rgb24 -s 1400x1400 -i /dev/urandom -frames:v 1 -q:v 2 "$cover"
  fi
  local ext
  for ext in "${ART_FORMATS[@]}"; do
    [ -f "$TPL/art.$ext" ] && [ -z "${FORCE:-}" ] && continue
    case "$ext" in
      flac) ffmpeg -hide_banner -loglevel error -y \
              -f lavfi -i "anullsrc=channel_layout=mono:sample_rate=44100" -t 1 \
              -i "$cover" -map 0:a:0 -map 1:v:0 -frames:v 1 \
              -c:a flac -c:v copy -disposition:v attached_pic "${META[@]}" "$TPL/art.$ext" ;;
      mp3)  ffmpeg -hide_banner -loglevel error -y \
              -f lavfi -i "anullsrc=channel_layout=mono:sample_rate=44100" -t 1 \
              -i "$cover" -map 0:a:0 -map 1:v:0 -frames:v 1 \
              -c:a libmp3lame -q:a 9 -c:v copy -id3v2_version 3 \
              -disposition:v attached_pic "${META[@]}" "$TPL/art.$ext" ;;
      m4a)  ffmpeg -hide_banner -loglevel error -y \
              -f lavfi -i "anullsrc=channel_layout=mono:sample_rate=44100" -t 1 \
              -i "$cover" -map 0:a:0 -map 1:v:0 -frames:v 1 \
              -c:a aac -b:a 32k -c:v copy -disposition:v attached_pic "${META[@]}" "$TPL/art.$ext" ;;
    esac
  done
  log "art templates ready (~$(du -h "$cover" | cut -f1) cover): ${ART_FORMATS[*]}"
}

# expected_count <dir> — number of regular files under a corpus dir, or 0.
expected_count() {
  [ -d "$1" ] || { echo 0; return 0; }
  find "$1" -type f 2>/dev/null | wc -l | tr -d ' '
}

# populate <dir> <count> <files-per-leaf>
# Distributes <count> copies round-robin across FORMATS into a 2-level tree.
populate() {
  local dir="$1" count="$2" per_leaf="$3"
  local existing; existing="$(expected_count "$dir")"
  if [ "$existing" -eq "$count" ] && [ -z "${FORCE:-}" ]; then
    log "$(basename "$dir"): already $count files (skip; FORCE=1 to rebuild)"
    return
  fi
  rm -rf "$dir"; mkdir -p "$dir"
  local i d s leaf ext src
  for ((i=0; i<count; i++)); do
    d=$(printf 'd%03d' $(( i / (per_leaf*per_leaf) )))
    s=$(printf 's%03d' $(( (i / per_leaf) % per_leaf )))
    leaf="$dir/$d/$s"; mkdir -p "$leaf"
    ext="${FORMATS[$(( i % ${#FORMATS[@]} ))]}"
    src="$TPL/template.$ext"
    cp "$src" "$(printf '%s/track_%06d.%s' "$leaf" "$i" "$ext")"
  done
  log "$(basename "$dir"): $count files across ${#FORMATS[@]} formats"
}

gen_tiny()   { build_templates; populate "$DATA/tiny"   "$TINY"   10; }
gen_small()  { build_templates; populate "$DATA/small"  "$SMALL"  16; }
gen_medium() { build_templates; populate "$DATA/medium" "$MEDIUM" 24; }
gen_large()  {
  echo "warning: 'large' generates $LARGE files (multi-GB). Ctrl-C to abort." >&2
  build_templates; populate "$DATA/large" "$LARGE" 30
}

# deep — same count spread over a deeper (4-level) tree.
gen_deep() {
  build_templates
  local dir="$DATA/deep" count="$DEEP"
  if [ "$(expected_count "$dir")" -eq "$count" ] && [ -z "${FORCE:-}" ]; then
    log "deep: already $count files (skip)"; return
  fi
  rm -rf "$dir"; mkdir -p "$dir"
  local i a b c ext leaf
  for ((i=0; i<count; i++)); do
    a=$(printf 'L1_%02d' $(( i % 20 )))
    b=$(printf 'L2_%02d' $(( (i/20) % 20 )))
    c=$(printf 'L3_%02d' $(( (i/400) % 20 )))
    leaf="$dir/$a/$b/$c"; mkdir -p "$leaf"
    ext="${FORMATS[$(( i % ${#FORMATS[@]} ))]}"
    cp "$TPL/template.$ext" "$(printf '%s/track_%06d.%s' "$leaf" "$i" "$ext")"
  done
  log "deep: $count files over a 4-level tree"
}

# mixed-format — an even split with every encodable format represented.
gen_mixed_format() {
  build_templates
  local dir="$DATA/mixed-format"
  local per=20 # files per format
  local count=$(( per * ${#FORMATS[@]} ))
  if [ "$(expected_count "$dir")" -eq "$count" ] && [ -z "${FORCE:-}" ]; then
    log "mixed-format: already $count files (skip)"; return
  fi
  rm -rf "$dir"; mkdir -p "$dir"
  local ext j
  for ext in "${FORMATS[@]}"; do
    mkdir -p "$dir/$ext"
    for ((j=0; j<per; j++)); do
      cp "$TPL/template.$ext" "$(printf '%s/%s/track_%03d.%s' "$dir" "$ext" "$j" "$ext")"
    done
  done
  log "mixed-format: $count files ($per × ${#FORMATS[@]} formats)"
}

gen_art() {
  echo "warning: 'art-heavy' generates $ART files with ~3 MB covers (multi-GB)." >&2
  build_templates; build_art_templates
  local dir="$DATA/art-heavy"
  if [ "$(expected_count "$dir")" -eq "$ART" ] && [ -z "${FORCE:-}" ]; then
    log "art-heavy: already $ART files (skip)"; return
  fi
  rm -rf "$dir"; mkdir -p "$dir"
  local i d ext
  for ((i=0; i<ART; i++)); do
    d=$(printf 'd%03d' $(( i / 200 )))
    mkdir -p "$dir/$d"
    ext="${ART_FORMATS[$(( i % ${#ART_FORMATS[@]} ))]}"
    cp "$TPL/art.$ext" "$(printf '%s/%s/track_%06d.%s' "$dir" "$d" "$i" "$ext")"
  done
  log "art-heavy: $ART files with embedded covers"
}

# corrupt — adversarial files that must not crash or block a scan.
gen_corrupt() {
  build_templates
  local dir="$DATA/corrupt"
  rm -rf "$dir"; mkdir -p "$dir"
  # A handful of valid files so a scan still yields real rows alongside errors.
  local ext i
  for ((i=0; i<8; i++)); do
    ext="${FORMATS[$(( i % ${#FORMATS[@]} ))]}"
    cp "$TPL/template.$ext" "$(printf '%s/valid_%02d.%s' "$dir" "$i" "$ext")"
  done
  : > "$dir/zero_bytes.mp3"                               # zero-byte
  printf 'this is not audio, just text\n' > "$dir/text.mp3" # text masquerading as mp3
  head -c 500 "$TPL/template.flac" > "$dir/truncated.flac"  # truncated audio
  head -c 1024 "$TPL/template.mp3" > "$dir/half.mp3"
  printf 'fake asf data' > "$dir/legacy.wma"                # intentionally unsupported
  cp "$TPL/template.ogg" "$dir/Ünïcödé—名前.ogg"             # unicode filename
  cp "$TPL/template.wav" "$dir/$(printf 'a%.0s' {1..200}).wav" # very long filename
  local ro="$dir/readonly.mp3"; cp "$TPL/template.mp3" "$ro"; chmod 0444 "$ro" # read-only
  # Pad to ~CORRUPT files with more truncated copies for volume.
  local n; n="$(expected_count "$dir")"
  while [ "$n" -lt "$CORRUPT" ]; do
    head -c $(( (n % 7) * 300 + 100 )) "$TPL/template.mp3" > "$(printf '%s/trunc_%03d.mp3' "$dir" "$n")"
    n=$(( n + 1 ))
  done
  log "corrupt: $(expected_count "$dir") adversarial files"
}

# dirty-save — valid files the save benchmark mutates then times.
gen_dirty() {
  build_templates
  populate "$DATA/dirty-500"  "$DIRTY_SMALL" 16
  populate "$DATA/dirty-2000" "$DIRTY_LARGE" 24
}

gen_all() {
  gen_tiny; gen_small; gen_medium; gen_deep; gen_mixed_format; gen_corrupt; gen_dirty
  log "generated 'all' (large + art-heavy excluded; pass them explicitly)"
}

main() {
  mkdir -p "$DATA"
  local args=("$@"); [ ${#args[@]} -eq 0 ] && args=(all)
  for c in "${args[@]}"; do
    case "$c" in
      tiny) gen_tiny ;;
      small) gen_small ;;
      medium) gen_medium ;;
      large) gen_large ;;
      deep) gen_deep ;;
      mixed-format) gen_mixed_format ;;
      art-heavy) gen_art ;;
      corrupt) gen_corrupt ;;
      dirty-save|dirty) gen_dirty ;;
      all) gen_all ;;
      *) echo "unknown corpus: $c" >&2; exit 1 ;;
    esac
  done
  log "bench-data total: $(du -sh "$DATA" 2>/dev/null | cut -f1)"
}

main "$@"
